language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

install:
   - pip install pep8

script:
   - find . -name \*.py -exec pep8 --ignore=E402 {} +
   - python test_math_operations.py