language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

install:
   - pip install pycodestyle
   - pip install ansible

before_script:
   - cd modules && find . -name \*.py -exec pycodestyle --ignore=E402 {} + && cd ..
   - ansible-playbook --syntax-check playbook.yml

script:
   - cd modules && python test_math_operations.py cd ..
   - ansible-playbook playbook.yml