language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

if: type = push AND pull_request
install:
   - pip install pycodestyle
   - pip install ansible

before_script:
   - find . -name \*.py -exec pycodestyle --ignore=E402 {} +
   - ansible-playbook --syntax-check playbook.yml

script:
   - python test_math_operations.py
   - ansible-playbook playbook.yml