language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

install:
   - pip install pep8
   - pip install ansible

before_script:
   - find . -name \modules/*.py -exec pep8 --ignore=E402 {} +
   - ansible-playbook --syntax-check playbook.yml

script:
   - python test_math_operations.py
   - ansible-playbook playbook.yml